options:
  drupal_version:
    type: string
    default: "7"
    description: "Drupal version, currently supported 6 and 7."
  drupal_profile:
    type: string
    default: "standard"
    description: "Profile name like standard, minimal or testing."
  drupal_site_name:
    type: string
    default: "Your fresh new site"
    description: "The Site Name, used when is a fresh install."
  drupal_admin_username:
    type: string
    default: "admin"
    description: "The default administrator user name."
  drupal_admin_email:
    type: string
    default: "admin@localhost.com"
    description: "The default administrator user name."
  drupal_admin_password:
    type: string
    default: ""
    description: "The default administrator password."
  drupal_source:
    type: string
    default: "drush"
    description: >
      From where the Drupal will be downloaded, currently supported a repository Git (Ex. git@host:path/repo.git) or 'drush' to download from the Drupal.org.
      Deploying from Git a Lullabot boilerplate based fork is expected https://github.com/TallerWebSolutions/drupal_boilerplate
  deploy_key:
    type: string
    default: ""
    description: "A deploy ssh key that is stored on the server and grants access to a repository (Git only)."
  install_drupal_boilerplate:
    type: boolean
    default: true
    description: "Use boilerplate."
  # drupal_boilerplate_destination:
  #   type: string
  #   default: "/var/www"
  #   description: "Destination path of the boilerplate."
  drupal_boilerplate_source:
    type: string
    default: "https://github.com/TallerWebSolutions/drupal_boilerplate.git"
    description: "Git repository of the boilerplate to install in case it's a new project from scratch."
  install_compass:
    type: boolean
    default: true
    description: "Install SASS/Compass, so that means ruby and rubygems will be installed."

