---
- hosts: all

  pre_tasks:
    - name: "Install tools like Wget, Git, Vim."
      apt: name={{ item }} state=present update_cache=yes
      tags:
        - install
        - upgrade-charm
        - config-changed 
      with_items:
        - wget
        - git-core
        - git-flow
        - curl
        - vim
        - sysstat
        - mktemp
        - aptitude
        - make
        - mysql-client
        - python-apt

    - name: "PPA for the last stable Nginx."
      apt_repository: repo=ppa:nginx/stable
      tags:
        - install
        - upgrade-charm
        - config-changed 


  roles:
    # Install Nginx with extras.
    - role: jdauphant.nginx
      tags:
        - packages
        - install
        - upgrade-charm
        - config-changed 

      ubuntu_pkg:
        - python-selinux
        - nginx-extras

    # Install and configure php-fpm.
    - role: nbz4live.php-fpm
      tags:
        - install
        - upgrade-charm
        - config-changed 

      php_fpm_apt_packages:
        - php5-fpm
        - php5-cli
        - php5-gd
        - php5-mysql
        - php5-mcrypt
        - php-pear
        - php-apc
        - php5-curl
        - php5-xdebug
        - php-mail

      php_fpm_pools:
        - name: www0
          user: www-data
          group: www-data
          listen: /var/run/php-fpm.sock
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www1
          user: www-data
          group: www-data
          listen: /var/run/php-fpm-zwei.sock
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www-bkp
          user: www-data
          group: www-data
          listen: /var/run/php-fpm-bkp.sock
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

    # Perusio's Nginx configurations.
    - role: pbuyle.nginx-drupal
      tags:
        - install
        - upgrade-charm
        - config-changed 
      nginx_drupal_use_drush: false
      nginx_drupal_microcache: false
      nginx_drupal_flv_streaming: false
      nginx_drupal_mp4_streaming: false
      nginx_drupal_aio: false
      nginx_drupal_http_core:
        client_max_body_size: "10m"
      nginx_drupal_upstream_servers:
        - "unix:/var/run/php-fpm.sock"
        - "unix:/var/run/php-fpm-zwei.sock"
      nginx_drupal_upstream_backup_servers:
        - "unix:/var/run/php-fpm-bkp.sock"
      nginx_drupal_sites:
        - file_name: default
          root: /var/www
          http:
            port: 80
          server_name: "_"

  tasks:
    - name: "Adding ubuntu user in the www-data group."
      user: name=ubuntu groups=www-data
      tags:
        - install
        - upgrade-charm
        - config-changed 

    - name: "Start Nginx e php-fpm"
      service: name={{ item }} state=started
      with_items:
        - nginx
        - php5-fpm
      tags:
        - start

    - name: "Stop Nginx e php-fpm"
      service: name={{ item }} state=stopped
      with_items:
        - nginx
        - php5-fpm
      tags:
        - stop




