---
- hosts: all

  pre_tasks:

    - name: "Default vars: db-mysql relation."
      include_vars: default/db-mysql-relation.yaml
      when: db_mysql__database is not defined or db_mysql__database == ''

    - name: "Copy private SSH key."
      shell: >
        echo "{{ deploy_key }}" > /home/ubuntu/.ssh/id_rsa
        creates=/home/ubuntu/.ssh/id_rsa
      when: >
        deploy_key != ''

    # Install dependencies.
    - name: "Install dependencies."
      include: tasks/install-dependencies.yaml
      tags:
        - install
        - upgrade-charm
        - config-changed

  roles:
    # Install: Nginx with extras.
    - role: jdauphant.nginx
      ubuntu_pkg:
        - python-selinux
        - nginx-extras
      tags:
        - install
        - upgrade-charm

    # Install and configure: PHP-FPM with 3 pools.
    - role: nbz4live.php-fpm
      tags:
        - install
        - upgrade-charm

      php_fpm_apt_packages:
        - php5-fpm
        - php5-cli
        - php5-gd
        - php5-mysql
        - php5-mcrypt
        - php-pear
        - php-apc
        - php5-curl
        - php5-xdebug
        - php-mail

      php_fpm_pools:
        - name: www0
          user: www-data
          group: www-data
          listen: /var/run/php-fpm.sock
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www1
          user: www-data
          group: www-data
          listen: /var/run/php-fpm-zwei.sock
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www-bkp
          user: www-data
          group: www-data
          listen: /var/run/php-fpm-bkp.sock
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

    # Install: Perusio's Nginx configurations.
    - role: pbuyle.nginx-drupal
      tags:
        - upgrade-charm
        - config-changed 
      nginx_drupal_use_drush: false
      nginx_drupal_microcache: false
      nginx_drupal_flv_streaming: false
      nginx_drupal_mp4_streaming: false
      nginx_drupal_aio: false
      nginx_drupal_http_core:
        client_max_body_size: "10m"
      nginx_drupal_upstream_servers:
        - "unix:/var/run/php-fpm.sock"
        - "unix:/var/run/php-fpm-zwei.sock"
      nginx_drupal_upstream_backup_servers:
        - "unix:/var/run/php-fpm-bkp.sock"
      nginx_drupal_sites:
        - file_name: default
          root: /var/www/docroot
          http:
            port: 80
          server_name: "_"

    # Install: PHP Composer.
    - role: pbuyle.php-composer
      composer_user: ubuntu
      composer_user_home: /home/ubuntu
      tags:
        - config-changed
        - upgrade-charm

    # Install: Drush.
    - role: geerlingguy.drush
      drush_version: 6.x
      tags:
        - config-changed
        - upgrade-charm

    # Install: Drupal Boilerplate.
    - role: sebas5384.drupal-boilerplate
      when: >
        drupal_source == "drush"
      tags:
        - config-changed
        - upgrade-charm

    # Install: Drupal.
    - role: sebas5384.drupal
      # @TODO: This can be part of the charm configs.
      drupal_path: /var/www/docroot
      drupal_db:
        driver: mysql
        database: "{{ db_mysql__database }}"
        host: "{{ db_mysql__host }}"
        user: "{{ db_mysql__user }}"
        password: "{{ db_mysql__password }}"
      tags:
        - config-changed
        - upgrade-charm
        - db-mysql-relation-changed
        - db-mysql-relation-departed


  tasks:
    - name: "Adding ubuntu user in the www-data group."
      user: name=ubuntu groups=www-data
      tags:
        - config-changed 
        - upgrade-charm

    - name: "Start Nginx e php-fpm."
      service: "name={{ item }} state=started"
      with_items:
        - nginx
        - php5-fpm
      tags:
        - start

    - name: "Stop Nginx e php-fpm."
      service: "name={{ item }} state=stopped"
      with_items:
        - nginx
        - php5-fpm
      tags:
        - stop

    - name: "Set permissions for the /var/www directory."
      file: path=/var/www owner=ubuntu group=www-data state=directory recurse=yes
      tags:
        - config-changed
        - upgrade-charm

    - name: "Set permissions for the user home directory."
      file: path=/home/ubuntu owner=ubuntu group=ubuntu recurse=yes
      tags:
        - config-changed
        - upgrade-charm

    # Charm Relations:
    # - include: tasks/db-mysql-relation.yaml
    #   tags:
    #     - db-mysql-relation-departed



