- hosts: all
  tasks:

    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - python-django
        - python-django-celery
      tags:
        - install
        - upgrade-charm

    - name: Put app code in place.
      git: repo=git://github.com/absoludity/charm-bootstrap-ansible.git
           dest=/srv/myapp
           version=HEAD
      tags:
        - install
        - config-changed

    - name: Start service
      debug: msg="You'd start some service here. The config 'string-option' has the value '{{ string_option }}'"
      tags:
        - start
        - config-changed

    - name: Stop service
      debug: msg="You'd stop some service here. The config 'string-option' is '{{ string_option }}'"
      tags:
        - stop
