---
- name: "Download Drupal using Drush."
  command: >
    drush dl -y drupal-{{ drupal_version }}
    --drupal-project-rename="{{ drupal_path | basename }}"
    --destination="{{ drupal_path }}/../"
    creates={{ drupal_path }}/index.php

# And finally install the Drupal via drush.
- name: "Install Drupal."
  command: >
    drush si -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_password }}
    --db-url={{ drupal_db.driver }}://{{ drupal_db.user }}:{{ drupal_db.password }}@{{ drupal_db.host }}/{{ drupal_db.database }}
    chdir={{ drupal_path }}
    creates={{ drupal_path }}/sites/default/settings.php
  register: drupal_new_installation_result
  when: drupal_db.database != "" and drupal_db.host != ""
