---
# Handle the random password.
- name: "Generate a random password."
  shell: >
    date +%s | sha256sum | base64 | head -c 8
  register: drupal_admin_password_result
  when: drupal_admin_password is not defined or drupal_admin_password == ""

- name: "Override Drupal Admin password fact."
  set_fact: "drupal_admin_password={{ drupal_admin_password_result.stdout }}"
  when: drupal_admin_password_result.stdout is defined

- debug: >
    msg="{{ drupal_admin_name }} password: {{ drupal_admin_password }}"
  when: drupal_admin_password_result.stdout is defined

# New project from Drupal.org
- name: "New project from Drupal.org"
  include: from-drush.yaml
  when: drupal_source == "drush"

# New project from Git.
- name: "New project from Git."
  include: from-git.yaml
  when: drupal_source | match("^(git|ssh|(http(s)?)).+\.git$")

# Permissions.
- name: "Set permissions properly on files directory."
  file: >
    path={{ drupal_path }}/sites/default/files
    mode=6774
    owner={{ drupal_www_owner }}
    group={{ drupal_www_group }}
    state=directory
    recurse=yes
  sudo: yes

- name: "Create contrib directories."
  file: >
    path={{ drupal_path }}/sites/all/{{ item }}/contrib
    owner={{ drupal_www_owner }}
    group={{ drupal_www_group }}
    state=directory
    recurse=yes
  sudo: yes
  with_items:
    - modules
    - themes

# Drupal Settings files.
- include: settings.php.yaml

- name: "Check Drupal status."
  shell: >
    drush status
    chdir={{ drupal_path }}
  register: drupal_status_result